edition = "2018"
tab_spaces = 2
newline_style = "Unix"
use_try_shorthand = true
max_width = 100
merge_derives = true
reorder_modules = true
use_field_init_shorthand = true
reorder_imports = true
match_block_trailing_comma = true
